spring:
  application:
    name: c-admin

  rabbitmq:
    #连接地址
    host: 127.0.0.1
    #端口号
    port: 5672
    #账号
    username: iotos_topMQ
    # 心跳  请求的心跳超时，以秒为单位； 零表示没有
    requested-heartbeat: 40
    #心跳开启
    keepalive: true
    #密码
    password: iotos_topMQ
    # 地址
    virtual-host: /IoTOSCard
    listener:
      simple:
        retry:
          #开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          #最大重试次数
          max-attempts: 1
          #重试间隔时间
          initial-interval: 3000
          # 手动应答 manual  自动应答 auto
        acknowledge-mode: auto


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/iotos_top?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: iotos_top
    password: iotos_top


  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 30s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

server:
  port: 8083



