# v1.2.1 版本升级到 v1.5.3 数据库需要增加文件



# [os_channel]-[2023-07-09]-[iotos]-[新增字段]
alter table os_channel add `card_left` decimal(18, 2) NOT NULL DEFAULT '0.00 ' COMMENT '归属卡-总剩余流量';
alter table os_channel add `card_total` decimal(18, 2) NOT NULL DEFAULT '0.00 ' COMMENT '归属卡-总流量';

# [os_card]-[2023-07-09]-[iotos]-[新增索引]
ALTER TABLE os_card ADD INDEX idx_channel_id (channel_id);

# [sys_job]-[2023-07-16]-[iotos]-[修改定时任务]
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'ryTask.ryNoParams', `cron_expression` = '0/10 * * * * ?', `misfire_policy` = '3', `concurrent` = '1', `status` = '1', `create_by` = 'admin', `create_time` = '2023-04-03 19:50:55', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `job_id` = 1 AND `job_name` = '系统默认（无参）' AND `job_group` = 'DEFAULT';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'ryTask.ryParams(\'ry\')', `cron_expression` = '0/15 * * * * ?', `misfire_policy` = '3', `concurrent` = '1', `status` = '1', `create_by` = 'admin', `create_time` = '2023-04-03 19:50:55', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `job_id` = 2 AND `job_name` = '系统默认（有参）' AND `job_group` = 'DEFAULT';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'ryTask.ryMultipleParams(\'ry\', true, 2000L, 316.50D, 100)', `cron_expression` = '0/20 * * * * ?', `misfire_policy` = '3', `concurrent` = '1', `status` = '1', `create_by` = 'admin', `create_time` = '2023-04-03 19:50:55', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `job_id` = 3 AND `job_name` = '系统默认（多参）' AND `job_group` = 'DEFAULT';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'initMQ.initMQConfig', `cron_expression` = '0/20 * * * * ?', `misfire_policy` = '3', `concurrent` = '1', `status` = '1', `create_by` = 'admin', `create_time` = '2023-04-13 13:56:11', `update_by` = '', `update_time` = NULL, `remark` = '' WHERE `job_id` = 100 AND `job_name` = 'RabbitMQ初始化' AND `job_group` = 'SYSTEM';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'performTask.clearUp', `cron_expression` = '0 30 0 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-04-25 15:04:11', `update_by` = 'admin', `update_time` = '2023-04-30 15:27:58', `remark` = '' WHERE `job_id` = 101 AND `job_name` = '清理执行任务' AND `job_group` = 'SYSTEM';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'synUpstreamCardTask.send', `cron_expression` = '0 45 0 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-01 10:58:09', `update_by` = '', `update_time` = '2023-05-01 22:13:55', `remark` = '' WHERE `job_id` = 102 AND `job_name` = '同步上游卡列表' AND `job_group` = 'SYNCHRONIZE';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'synUpstreamCardTask.verificationTotal', `cron_expression` = '0 0/30 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-01 21:44:54', `update_by` = 'admin', `update_time` = '2023-05-02 16:21:34', `remark` = '' WHERE `job_id` = 103 AND `job_name` = '同步上游卡列表总数核验' AND `job_group` = 'SYNCHRONIZE';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'synUpstreamCardTask.contrastDifference', `cron_expression` = '0 0/5 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-02 11:35:23', `update_by` = 'admin', `update_time` = '2023-05-02 16:21:52', `remark` = '' WHERE `job_id` = 104 AND `job_name` = '同步上游卡列表对比差异' AND `job_group` = 'SYNCHRONIZE';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'synUpstreamCardTask.newDataImport', `cron_expression` = '0 30 9 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-02 13:13:03', `update_by` = '', `update_time` = '2023-05-02 13:13:11', `remark` = '' WHERE `job_id` = 105 AND `job_name` = '同步上游卡号导入卡列表' AND `job_group` = 'SYNCHRONIZE';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'synUpstreamCardTask.synDataRecovery', `cron_expression` = '0 0/1 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-02 16:11:55', `update_by` = 'admin', `update_time` = '2023-05-02 16:20:30', `remark` = '' WHERE `job_id` = 106 AND `job_name` = '同步上游卡号数据修复' AND `job_group` = 'SYNCHRONIZE';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'initDBTask.monthlyMigration(-1)', `cron_expression` = '0 0 1 1 * ? *', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-05 16:16:20', `update_by` = 'admin', `update_time` = '2023-05-13 10:41:02', `remark` = '' WHERE `job_id` = 107 AND `job_name` = '初始化月用量记录' AND `job_group` = 'MONTH';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'pollingStartTask.run', `cron_expression` = '0 10 0 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-09 08:10:42', `update_by` = '', `update_time` = '2023-05-09 08:10:50', `remark` = '' WHERE `job_id` = 108 AND `job_name` = '轮询执行' AND `job_group` = 'POLLING';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'pollingStartTask.compensation(\'4,5\',\'1\',300,\'synFlow\')', `cron_expression` = '0 0/1 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-14 17:15:47', `update_by` = 'admin', `update_time` = '2023-05-14 20:55:52', `remark` = '' WHERE `job_id` = 109 AND `job_name` = '轮询补偿-用量-已激活/已停机' AND `job_group` = 'POLLING';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'pollingStartTask.initTime', `cron_expression` = '0 0/10 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-14 17:54:54', `update_by` = 'admin', `update_time` = '2023-07-15 22:17:21', `remark` = '' WHERE `job_id` = 110 AND `job_name` = '初始化补偿 记录时间' AND `job_group` = 'POLLING';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'pollingStartTask.compensation(\'4,5\',\'1\',300,\'synStatus\')', `cron_expression` = '0 0/1 * * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-14 20:42:45', `update_by` = 'admin', `update_time` = '2023-05-14 20:48:59', `remark` = '' WHERE `job_id` = 111 AND `job_name` = '轮询补偿-状态-已激活/已停机' AND `job_group` = 'POLLING';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'pollingStartTask.compensation(\'0,1,2,3\',\'1\',300,\'synStatus\')', `cron_expression` = '0 10 0/1 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-14 20:43:58', `update_by` = 'admin', `update_time` = '2023-05-14 20:55:50', `remark` = '' WHERE `job_id` = 112 AND `job_name` = '轮询补偿-状态-未知/库存/可测试/待激活' AND `job_group` = 'POLLING';
UPDATE `iotos_top`.`sys_job` SET `invoke_target` = 'frontPageTask.generate(100)', `cron_expression` = '0 5 0 * * ?', `misfire_policy` = '1', `concurrent` = '1', `status` = '0', `create_by` = 'admin', `create_time` = '2023-05-22 20:52:04', `update_by` = '', `update_time` = '2023-05-22 20:52:08', `remark` = '' WHERE `job_id` = 113 AND `job_name` = '总部首页数据生成' AND `job_group` = 'SYSTEM';

# [sys_job]-[2023-07-16]-[iotos]-[修改定时任务]
INSERT INTO `iotos_top`.`sys_job` (`job_id`, `job_name`, `job_group`, `invoke_target`, `cron_expression`, `misfire_policy`, `concurrent`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (114, '通道同步卡数量', 'SYNCHRONIZE', 'statisticsTask.cardCount', '0 10 0/2 * * ?', '1', '1', '0', 'admin', '2023-07-09 16:25:24', '', '2023-07-09 16:25:27', '');
INSERT INTO `iotos_top`.`sys_job` (`job_id`, `job_name`, `job_group`, `invoke_target`, `cron_expression`, `misfire_policy`, `concurrent`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (115, '通道同步卡用量', 'DEFAULT', 'statisticsTask.sumUsed', '0 20 0/2 * * ?', '1', '1', '0', 'admin', '2023-07-09 16:26:23', '', '2023-07-09 16:26:25', '');
INSERT INTO `iotos_top`.`sys_job` (`job_id`, `job_name`, `job_group`, `invoke_target`, `cron_expression`, `misfire_policy`, `concurrent`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (116, '清理重复会话记录', 'DEFAULT', 'cardSessionTask.clearUp(7)', '0 40 0 * * ?', '1', '1', '0', 'admin', '2023-07-15 20:31:16', 'admin', '2023-07-16 11:57:50', '');
INSERT INTO `iotos_top`.`sys_job` (`job_id`, `job_name`, `job_group`, `invoke_target`, `cron_expression`, `misfire_policy`, `concurrent`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (117, '轮询补偿-状态-未知', 'DEFAULT', 'pollingStartTask.compensation(\'0\',\'1\',10000,\'synStatus\')', '0 0/1 * * * ?', '1', '1', '0', 'admin', '2023-07-15 22:19:21', 'admin', '2023-07-15 22:19:51', '');
INSERT INTO `iotos_top`.`sys_job` (`job_id`, `job_name`, `job_group`, `invoke_target`, `cron_expression`, `misfire_policy`, `concurrent`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (118, '清理上游已经同步卡号', 'DEFAULT', 'upstreamCardTask.clearUp', '0 10 12 1/7 * ?', '1', '1', '0', 'admin', '2023-07-16 11:59:53', '', '2023-07-16 11:59:56', '');


# [sys_dict_type]-[2023-07-16]-[iotos]-[字典新增]
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (134, '智能诊断查询条件', 'diagnosis_sel_type', '0', 'admin', '2023-07-10 21:02:59', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (135, 'ECV5服务状态', 'ecv5_service_status', '0', 'admin', '2023-07-11 22:33:30', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (136, 'ECV5通信功能服务类型', 'ecv5_service_type', '0', 'admin', '2023-07-11 22:37:43', 'admin', '2023-07-11 22:37:55', NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (137, 'ECV5限制区域', 'ecv5_restricted_area', '0', 'admin', '2023-07-12 20:42:56', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (138, 'ECV5变更状态类型', 'ecv5_change_status', '0', 'admin', '2023-07-12 23:30:25', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (139, 'ECV5开关机状态', 'ecv5_onoff_status', '0', 'admin', '2023-07-13 23:10:24', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_type` (`dict_id`, `dict_name`, `dict_type`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (140, 'ECV5机卡分离状态', 'ecv5_bind_status', '0', 'admin', '2023-07-14 22:50:06', '', NULL, NULL);


INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (288, 7, '会话历史导出', 'cardSessionExport', 'iotos_task_type', NULL, 'default', 'N', '0', 'admin', '2023-07-10 14:56:50', 'admin', '2023-07-10 14:56:55', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (289, 4, 'cardSessionExport', '14', 'task_flie_expiration_date', NULL, 'default', 'N', '0', 'admin', '2023-07-10 14:57:19', 'admin', '2023-07-10 14:57:38', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (290, 0, '会话历史记录', '_cardSessionExport', 'iotos_task_name', NULL, 'default', 'N', '0', 'admin', '2023-07-10 14:58:32', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (291, 0, '编号', '0', 'diagnosis_sel_type', NULL, 'default', 'N', '0', 'admin', '2023-07-10 21:13:01', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (292, 1, 'ICCID', '1', 'diagnosis_sel_type', NULL, 'default', 'N', '0', 'admin', '2023-07-10 21:13:23', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (293, 2, 'MSISDN', '2', 'diagnosis_sel_type', NULL, 'default', 'N', '0', 'admin', '2023-07-10 21:13:34', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (294, 3, 'IMSI', '3', 'diagnosis_sel_type', NULL, 'default', 'N', '0', 'admin', '2023-07-10 21:13:47', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (295, 0, '暂停', '0', 'ecv5_service_status', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:33:44', 'admin', '2023-07-11 22:34:03', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (296, 1, '恢复', '1', 'ecv5_service_status', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:33:51', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (297, 1, '基础语音通信服务', '01', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:38:15', 'admin', '2023-07-11 22:39:42', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (298, 8, '短信基础服务', '08', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:38:28', 'admin', '2023-07-11 22:39:37', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (299, 10, '国际漫游服务', '10', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:38:40', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (300, 11, '数据通信服务', '11', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:38:49', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (301, 12, '短信基础服务(5G  SA)', '12', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:39:09', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (302, 13, 'VOLTE 语音基础服务(5G SA)', '13', 'ecv5_service_type', NULL, 'default', 'N', '0', 'admin', '2023-07-11 22:39:30', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (303, 0, '北京', '100', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (304, 1, '广东', '200', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (305, 2, '上海', '210', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (306, 3, '天津', '220', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (307, 4, '重庆', '230', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (308, 5, '辽宁', '240', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (309, 6, '江苏', '250', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (310, 7, '湖北', '270', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (311, 8, '四川', '280', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (312, 9, '陕西', '290', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (313, 10, '河北', '311', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (314, 11, '山西', '351', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (315, 12, '河南', '371', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (316, 13, '吉林', '431', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (317, 31, '黑龙江', '451', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', 'admin', '2023-07-12 21:00:10', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (318, 32, '内蒙古', '471', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', 'admin', '2023-07-12 21:00:04', NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (319, 16, '山东', '531', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (320, 17, '安徽', '551', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (321, 18, '浙江', '571', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (322, 19, '福建', '591', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (323, 20, '湖南', '731', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (324, 21, '广西', '771', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (325, 22, '江西', '791', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (326, 23, '贵州', '851', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (327, 24, '云南', '871', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (328, 25, '西藏', '891', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (329, 26, '海南', '898', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (330, 27, '甘肃', '931', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (331, 28, '宁夏', '951', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (332, 29, '青海', '971', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (333, 30, '新疆', '991', 'ecv5_restricted_area', NULL, 'default', 'N', '0', 'admin', '2023-07-12 20:43:08', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (334, 1, '待激活', '1', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:30:38', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (335, 2, '已激活', '2', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:30:45', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (336, 4, '停机', '4', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:30:52', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (337, 6, '可测试', '6', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:31:00', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (338, 7, '库存', '7', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:31:07', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (339, 8, '预销户', '8', 'ecv5_change_status', NULL, 'default', 'N', '0', 'admin', '2023-07-12 23:31:16', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (340, 0, '关机', '0', 'ecv5_onoff_status', NULL, 'default', 'N', '0', 'admin', '2023-07-13 23:10:40', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (341, 1, '开机', '1', 'ecv5_onoff_status', NULL, 'default', 'N', '0', 'admin', '2023-07-13 23:10:48', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (342, 0, '已分离', '0', 'ecv5_bind_status', NULL, 'default', 'N', '0', 'admin', '2023-07-14 22:50:20', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (343, 1, '未分离', '1', 'ecv5_bind_status', NULL, 'default', 'N', '0', 'admin', '2023-07-14 22:50:28', '', NULL, NULL);
INSERT INTO `iotos_top`.`sys_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (344, 2, '查询失败', '2', 'ecv5_bind_status', NULL, 'default', 'N', '0', 'admin', '2023-07-14 22:50:35', '', NULL, NULL);


# [sys_menu]-[2023-07-16]-[iotos]-[菜单新增]
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2038, '智能诊断', 2001, 2, 'diagnosis', 'iotos/connect/card/diagnosis', NULL, 1, 0, 'C', '0', '0', 'iotos:card:diagnosis', '#', 'admin', '2023-07-10 20:52:32', '', NULL, '', 'diagnosis');
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2040, '资费详情实时查询', 2038, 1, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:queryApiTariff', '#', 'admin', '2023-07-13 21:11:28', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2041, '单卡停机原因查询', 2038, 2, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:querySimStopReason', '#', 'admin', '2023-07-13 21:11:44', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2042, '单卡通信功能开通查询', 2038, 3, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:querySimProduct', '#', 'admin', '2023-07-13 21:12:02', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2043, '物联卡区域限制状态查询', 2038, 4, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:querySimRLStatus', '#', 'admin', '2023-07-13 21:12:20', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2044, '物联卡区域限制区域查询', 2038, 5, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:querySimRLArea', '#', 'admin', '2023-07-13 21:16:14', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2045, '单卡开关机状态实时查询', 2038, 6, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:queryOnOffStatus', '#', 'admin', '2023-07-13 21:16:28', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2046, '物联卡机卡分离状态查询', 2038, 7, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:queryCardBindStatus', '#', 'admin', '2023-07-16 13:52:33', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2047, '单卡状态变更历史查询', 2038, 8, '', NULL, NULL, 1, 0, 'F', '0', '0', 'os:card:querySimChangeHistory', '#', 'admin', '2023-07-16 13:52:47', '', NULL, '', NULL);
INSERT INTO `iotos_top`.`sys_menu` (`menu_id`, `menu_name`, `parent_id`, `order_num`, `path`, `component`, `query`, `is_frame`, `is_cache`, `menu_type`, `visible`, `status`, `perms`, `icon`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`, `tcode`) VALUES (2048, '卡号匹对', 2038, 9, '', NULL, NULL, 1, 0, 'F', '0', '0', 'iotos:card:cardMatch', '#', 'admin', '2023-07-16 13:53:10', '', NULL, '', NULL);

